# Generated by Django 3.2.9 on 2022-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainbanner',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
