# Generated by Django 3.2.9 on 2021-12-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_linktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='linktype',
            field=models.CharField(choices=[('Whatsapp', 'Whatsapp'), ('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Youtube', 'Youtube'), ('TikTok', 'TikTok'), ('Instagram', 'Instagram')], max_length=100, verbose_name='Platforma'),
        ),
    ]
