# Generated by Django 3.2.9 on 2022-02-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_wp_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Qrup haqqında'),
        ),
        migrations.AlterField(
            model_name='post',
            name='wp_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='linker wp '),
        ),
    ]
