# Generated by Django 3.2.9 on 2022-02-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20220212_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sssss',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='post_views',
        ),
    ]
