# Generated by Django 3.2.9 on 2022-02-16 19:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20220213_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='1', force_format='JPEG', keep_meta=True, quality=80, size=[1280, 720], upload_to='', verbose_name='Sekil'),
            preserve_default=False,
        ),
    ]
