# Generated by Django 4.0.1 on 2022-05-02 07:00

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_views',
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Baxış sayı'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=80, size=[1280, 720], upload_to='', verbose_name='Sekil'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=10, verbose_name='Qrupun adı'),
        ),
    ]
